on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 22
        - run: |
              keytool -genkey -keystore release.jks -keyalg RSA -keysize 2048 -validity 10000 -storepass 123456 -alias release -dname 'CN=(名字与姓氏), OU=(组织单位名称), O=(组织名称), L=(城市或区域名称), ST=(州或省份名称), C=(单位的两字母国家代码)'
              mkdir res
              $ANDROID_HOME/build-tools/34.0.0/aapt2 compile --dir res -o out.zip
              $ANDROID_HOME/build-tools/34.0.0/aapt2 link out.zip -I $ANDROID_HOME/platforms/android-34/android.jar --manifest AndroidManifest.xml -o out.apk
              gradle --warning-mode all copyDependencies
              javac -Xlint:deprecation -cp $ANDROID_HOME/platforms/android-34/android.jar:copyDependencies/* com/main/*.java
              java -cp $ANDROID_HOME/build-tools/34.0.0/lib/d8.jar com.android.tools.r8.D8 com/main/*.class copyDependencies/*.jar --lib $ANDROID_HOME/platforms/android-34/android.jar --release 
              $ANDROID_HOME/build-tools/34.0.0/aapt add out.apk classes.dex assets/*
              $ANDROID_HOME/build-tools/34.0.0/zipalign 4 out.apk tmp.apk
              mv tmp.apk out.apk
              java -jar $ANDROID_HOME/build-tools/34.0.0/lib/apksigner.jar sign --ks release.jks --ks-pass pass:123456 out.apk
              #id=$(curl -H authorization:token\ ${{secrets.GITHUB_TOKEN}} https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | python -c 'import json,sys,builtins; builtins.print(json.loads(sys.stdin.read()).get("id"))')
              #curl -X DELETE -H authorization:token\ ${{secrets.GITHUB_TOKEN}} https://api.github.com/repos/$GITHUB_REPOSITORY/releases/$id
        - uses: actions/upload-artifact@main
          with:
              path: out.apk
    clean:
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
        - run: |
              sudo apt update
              sudo apt install -y --no-install-recommends python3-aiohttp
              curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python3 - ${{secrets.GITHUB_TOKEN}}
