on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 22
        - run: |
              curl -O https://dev.azure.com/chaowenguoback/ci/_apis/git/repositories/ci/items?path=/timebuckwall.mjs
              curl -O https://dev.azure.com/chaowenguoback/ci/_apis/git/repositories/ci/items?path=/timewall.mjs
              sudo apt install -y --no-install-recommends node-commander lxde
              mkdir ~/.ssh/
              echo '${{secrets.id_ed25519}}' > ~/.ssh/id_ed25519
              chmod 400 ~/.ssh/id_ed25519
              cat ~/.ssh/id_ed25519
              npm install playwright-chromium@1.40.0 lodash-es jsdom sqlite3 sqlite ssh2-promise html-entities tough-cookie unraw ioredis json5 webdriverio git+https://github.com/fancy45daddy/tlsclient.js
              awk -i inplace '/^import /{seen++} seen && !/^import /{print "import formDataToStream from \x27./helpers/formDataToStream.js\x27;"; seen=0}1' $(npm root)/axios/lib/axios.js
              awk -i inplace '!found && /axios.default/ {print "axios.formDataToStream = formDataToStream;"; found=1}1' $(npm root)/axios/lib/axios.js
              ssh ubuntu@23.96.21.170 ls
              #node timewall.mjs --redis ${{secrets.redis}} --ip 23.96.21.170
              #Xvfb :99 &
              #DISPLAY=:99 startlxde &
              #sleep 10
              #DISPLAY=:99 node timebuckwall.mjs --browserstack ${{secrets.browserstack}} --gemini ${{secrets.gemini}} --redis ${{secrets.redis}} --ip 23.96.21.170
    clean:
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
        - run: |
              sudo apt update
              sudo apt install -y --no-install-recommends python3-aiohttp
              curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python3 - ${{secrets.GITHUB_TOKEN}}
